spring:
  datasource:
    username: root
    password: hff19970209...
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useSSL=false&serverTimezone=UTC&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      filters: stat,wall,slf4j
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
  thymeleaf:
    mode: HTML
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.cookie.pojo
  mapper-locations: classpath:mapper-xml/*.xml
#
#mapper:
#  mappers: com.cookie.mapper
#  not-empty: false
#  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql